CREATE DATABASE usuarios;

CREATE TABLE usuarios.cuenta (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, usuario VARCHAR(200), nombre VARCHAR(200), clave VARCHAR(200), ruta_foto VARCHAR(200));

CREATE TABLE usuarios.publicaciones (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, usuario VARCHAR(200), ruta VARCHAR(200), contenido VARCHAR(200), formato VARCHAR(200));

CREATE TABLE usuarios.solicitudes (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, usuario VARCHAR(200), destino VARCHAR(200), respuesta VARCHAR(200));

CREATE TABLE usuarios.amigos (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, usuario VARCHAR(200), usuario2 VARCHAR(200));

CREATE TABLE usuarios.chat (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, usuario VARCHAR(200), destino VARCHAR(200), mensaje VARCHAR(200), fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE usuarios.comentarios (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, id_publicacion VARCHAR(200), texto VARCHAR(200), usuario VARCHAR(200), fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE usuarios.usuarios_online (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, fecha INT NOT NULL, usuario VARCHAR(200) NOT NULL );

CREATE TABLE usuarios.cifrado (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, algoritmo VARCHAR(200), clave VARCHAR(200), modo VARCHAR(200), vector VARCHAR(200));